project:
  type: website

execute:
  freeze: auto

website:
  title: "新台嘉の部落格"
  site-url: https://blog.sintaika.com
  description: "新台嘉的作者們寫寫嘉義的歷史、文化、技術、設計與社會。"
  navbar:
    right:
      - about.qmd
      - icon: facebook
        href: https://www.facebook.com/sintaikaka
      - icon: instagram
        href: https://www.instagram.com/sintaikaka/
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

editor: visual