project:
  type: website

execute:
  freeze: auto

website:
  title: "新台嘉の部落格"
  navbar:
    right:
      - about.qmd
      - icon: facebook
        href: https://www.facebook.com/sintaikaka
      - icon: instagram
        href: https://www.instagram.com/sintaikaka/
format:
  html:
    theme:
      light: minty
      dark: vapor
    css: styles.css

editor: visual